"""empty message

Revision ID: 743d21d8d953
Revises: 4e3f930afa97
Create Date: 2025-04-22 22:31:01.658029-05:00

"""
from typing import Sequence, Union
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743d21d8d953'
down_revision: Union[str, None] = '4e3f930afa97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('country', sqlalchemy_utils.types.country.CountryType(length=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'country')
    # ### end Alembic commands ###
