"""empty message

Revision ID: ebaa7aa2a1b7
Revises: 7dbcdcc1f64a
Create Date: 2025-05-17 02:00:58.293195-05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebaa7aa2a1b7'
down_revision: Union[str, None] = '7dbcdcc1f64a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotions', 'expire',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotions', 'expire',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
