"""empty message

Revision ID: 7dbcdcc1f64a
Revises: e57d5cc62fb9
Create Date: 2025-05-03 14:26:31.711238-05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dbcdcc1f64a'
down_revision: Union[str, None] = 'e57d5cc62fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'google_maps_embed_url',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'google_maps_embed_url',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               nullable=False)
    # ### end Alembic commands ###
