"""empty message

Revision ID: 42322f45b84c
Revises: 743d21d8d953
Create Date: 2025-05-03 12:02:21.953456-05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42322f45b84c'
down_revision: Union[str, None] = '743d21d8d953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('google_maps_embed_url', sa.String(), server_default='', nullable=False))
    op.drop_column('locations', 'google_embed_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('google_embed_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('locations', 'google_maps_embed_url')
    # ### end Alembic commands ###
