"""empty message

Revision ID: 4e3f930afa97
Revises: db9d0cae31eb
Create Date: 2025-04-22 21:46:36.874309-05:00

"""
from typing import Sequence, Union
from app.models import SmartString
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3f930afa97'
down_revision: Union[str, None] = 'db9d0cae31eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('normal_str', sa.String(), nullable=False))
    op.add_column('tests', sa.Column('my_str', SmartString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'my_str')
    op.drop_column('tests', 'normal_str')
    # ### end Alembic commands ###
