"""empty message

Revision ID: e57d5cc62fb9
Revises: 42322f45b84c
Create Date: 2025-05-03 13:11:48.088522-05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy_file
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e57d5cc62fb9'
down_revision: Union[str, None] = '42322f45b84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('image', sqlalchemy_file.types.ImageField(none_as_null=True), nullable=False))
    op.add_column('tests', sa.Column('file', sqlalchemy_file.types.FileField(none_as_null=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'file')
    op.drop_column('tests', 'image')
    # ### end Alembic commands ###
